### ISSUE TITLE
更新了油猴脚本后 布局很挤 原来的空白部分被去除了

### ISSUE THREAD

**Issue by carve-myself** [Sec-ant/weread-scraper#15]
更新前:
![image](https://github.com/Sec-ant/weread-scraper/assets/68720524/1ca7c9cd-4127-48f2-87b3-01cb628c4c4c)
![image](https://github.com/Sec-ant/weread-scraper/assets/68720524/899cbdf5-ecca-42a1-aea0-ed202b2ba617)

更新后:
![image](https://github.com/Sec-ant/weread-scraper/assets/68720524/eaa98dd7-0a27-4738-8f6e-73b87dd47c8f)
![image](https://github.com/Sec-ant/weread-scraper/assets/68720524/d8506a21-4bf1-4e02-a77c-54b007f10d0b)

**Comment by Sec-ant** [comment]
请提供一下书籍的链接、脚本版本

**Comment by Sec-ant** [comment]
1.1.1 版本添加了向旧版本兼容的 `page-break-after` css 规则
