### ISSUE TITLE
希望增加导出完全离线版html文件功能

### ISSUE THREAD

**Issue by vstephenzhou** [Sec-ant/weread-scraper#19]
作者你好,使用0.5版本脚本下载同一本书(例如镜花缘插图版)体积为21MB,现在使用1.1.1版本下载同一本图书,只有1.5MB,
去比较了两个版本导出来的文件,html里面内容,图片确实都是链接,但是0.5版本初始大小尺寸显示貌似比1.1.1版本的好点.
使用princexml转换为pdf后显示图片大小也不一样.

另外请作者可能的话增加一个能导出离线显示图片的功能,类似于SingleFile这个扩展一样, 以防网站修改导致以前的html无法加载图片,或者无网络的情况无法查看导出的图书内的图片, 并且使用princexml这个转换时候不联网转换出的文件没有图片.
非常感谢.
[html.zip](https://github.com/Sec-ant/weread-scraper/files/11988661/html.zip)
[镜花缘（全两册·插图版）脚本1.1.1版.pdf](https://github.com/Sec-ant/weread-scraper/files/11988662/1.1.1.pdf)
[镜花缘（全两册·插图版）脚本0.5版.pdf](https://github.com/Sec-ant/weread-scraper/files/11988663/0.5.pdf)

**Comment by Sec-ant** [comment]
1. 首先，使用这两个版本的脚本获得的 HTML 文件，或者经过 PrinceXML 导出的 PDF 文件，对于同一张插图，它们拿到的图片文件是完全一致的，不存在图片质量上的区别，这是我用 Adobe Acrobat 把两个 PDF 中的图片文件分别保存下来再比较得到的结果：
    ![image](https://github.com/Sec-ant/weread-scraper/assets/10386119/cbdf016f-8e0a-4ee8-9ac6-06192f434543)

2. 使用这两个版本获得的文件，对于同一张插图，图片的显示大小确实存在区别，这一点是由 HTML 样式决定的，它不会改变图片本身的大小，但它会改变图片的显示尺寸。对于 1.1.1 版本（1.0.0 版本以上均适用），图片的显示尺寸还会受到窗口缩放影响，这个问题我是打算解决的。解决这一问题后，图片的显示尺寸不会受到抓取时网页窗口大小的影响，理论上也会和 0.x 版本的结果保持一致，可以等下一个版本的更新。

3. 在单文件导出的前提下，支持离线图片意味着需要将图片本身内容编码为 Base64 URL 嵌入到文件中，这意味着：
   1. 抓取书籍内容时需要同时抓取所有的图片内容，会降低抓取速度；
   2. 图片内容本身会占用掉大部分的空间，且 Base64 编码的数据是原始数据体积的 4/3，最后的文件体积会比较大。
   不过离线版这个需求是合理的，我打算默认设置保持不变，即不抓取图片数据，并提供一个选项让用户可以选择同时抓取图片数据。

**Comment by vstephenzhou** [comment]
> 1. 首先，使用这两个版本的脚本获得的 HTML 文件，或者经过 PrinceXML 导出的 PDF 文件，对于同一张插图，它们拿到的图片文件是完全一致的，不存在图片质量上的区别，这是我用 Adobe Acrobat 把两个 PDF 中的图片文件分别保存下来再比较得到的结果：
>    ![image](https://user-images.githubusercontent.com/10386119/251941609-cbdf016f-8e0a-4ee8-9ac6-06192f434543.png)
> 2. 使用这两个版本获得的文件，对于同一张插图，图片的显示大小确实存在区别，这一点是由 HTML 样式决定的，它不会改变图片本身的大小，但它会改变图片的显示尺寸。对于 1.1.1 版本（1.0.0 版本以上均适用），图片的显示尺寸还会受到窗口缩放影响，这个问题我是打算解决的。解决这一问题后，图片的显示尺寸不会受到抓取时网页窗口大小的影响，理论上也会和 0.x 版本的结果保持一致，可以等下一个版本的更新。
> 3. 在单文件导出的前提下，支持离线图片意味着需要将图片本身内容编码为 Base64 URL 嵌入到文件中，这意味着：
>    
>    1. 抓取书籍内容时需要同时抓取所有的图片内容，会降低抓取速度；
>    2. 图片内容本身会占用掉大部分的空间，且 Base64 编码的数据是原始数据体积的 4/3，最后的文件体积会比较大。
>    
>    不过离线版这个需求是合理的，我打算默认设置保持不变，即不抓取图片数据，并提供一个选项让用户可以选择同时抓取图片数据，且仅支持 `<img>` 元素，这个也要等新版本更新。
> 
> 此外你提供的 pdf 文件可能版本号标反了，但是不影响上面所说的内容。

感谢作者耐心解答，期待更新发布。

**Comment by Sec-ant** [comment]
1.2.0 版本添加了内联图片选项（Inline Images），可以在抓取过程中同时下载书中的插图，并在离线环境下正常浏览图片内容。开启该选项后抓取速度会减慢，且对于插图较多的书籍其文件体积会显著增加，因此默认不开启。

其中✔表示开启，✘表示关闭，鼠标点击该选项即可切换开启/关闭状态。

![image](https://github.com/Sec-ant/weread-scraper/assets/10386119/546934cc-52f4-406b-85d2-bc4ec67b6cbf)

对于另外一个问题，按照目前的抓取方式，很难有有效的手段处理图片显示尺寸，暂时没办法解决，未来抓取方式变更后会重新考虑这一点。
