### ISSUE TITLE
最新版本离线图片很模糊～作者

### ISSUE THREAD

**Issue by Adver23** [Sec-ant/weread-scraper#21]
![8FC28A15-3BF5-4ABA-9DE1-1E620688E67F](https://github.com/Sec-ant/weread-scraper/assets/131567072/ce8aa30f-8e9f-4be3-aa18-bf48793f8df5)
![2ED1440E-4B7D-4F80-8564-FBFA55AD6147](https://github.com/Sec-ant/weread-scraper/assets/131567072/9ebc7c4e-e846-47df-aaa9-81e537403715)
 https://weread.qq.com/web/reader/93132980813ab7dcdg013c56
 
谷歌浏览器
离线图片很模糊

**Comment by Sec-ant** [comment]
请问这个截图是 HTML 格式的文件还是 PDF 格式的文件？我这里抓取完毕后不论是 HTML 还是打印为 PDF 图片都是很清晰的。
![image](https://github.com/Sec-ant/weread-scraper/assets/10386119/71d30c30-7db4-40c0-bb5b-ef9f42c9b190)

**Comment by Adver23** [comment]
> 请问这个截图是 HTML 格式的文件还是 PDF 格式的文件？我这里抓取完毕后不论是 HTML 还是打印为 PDF 图片都是很清晰的。
> ![image](https://user-images.githubusercontent.com/10386119/255313635-71d30c30-7db4-40c0-bb5b-ef9f42c9b190.png)

不好意思，是工具转换为epub后很模糊😂原文件看了，确实是高清的……有什么好的转换工具推荐吗

**Comment by Sec-ant** [comment]
> 不好意思，是工具转换为epub后很模糊😂原文件看了，确实是高清的……有什么好的转换工具推荐吗

用 pandoc 转效果还可以，图片是清晰的，也可以自己生成目录。但是不能用 inline images 选项，因为 pandoc 遇到体积很大的 html 文件时会长时间不响应。它在转换时会自动下载图片，所以转换完依然是可以离线阅读的。

![image](https://github.com/Sec-ant/weread-scraper/assets/10386119/a4316e58-2210-495c-afd7-083be82073b8)

**Comment by Adver23** [comment]
> > 不好意思，是工具转换为epub后很模糊😂原文件看了，确实是高清的……有什么好的转换工具推荐吗
> 
> 用 pandoc 转效果还可以，图片是清晰的，也可以自己生成目录。但是不能用 inline images 选项，因为 pandoc 遇到体积很大的 html 文件时会长时间不响应。它在转换时会自动下载图片，所以转换完依然是可以离线阅读的。
> 
> ![image](https://user-images.githubusercontent.com/10386119/255315560-a4316e58-2210-495c-afd7-083be82073b8.png)

感谢，我试试

**Comment by Adver23** [comment]
> > > 不好意思，是工具转换为epub后很模糊😂原文件看了，确实是高清的……有什么好的转换工具推荐吗
> > 
> > 
> > 用 pandoc 转效果还可以，图片是清晰的，也可以自己生成目录。但是不能用 inline images 选项，因为 pandoc 遇到体积很大的 html 文件时会长时间不响应。它在转换时会自动下载图片，所以转换完依然是可以离线阅读的。
> > ![image](https://user-images.githubusercontent.com/10386119/255315560-a4316e58-2210-495c-afd7-083be82073b8.png)
> 
> 感谢，我试试

命令语句是什么呀，作者，试了txt转doc，没看到HTML转epub的命令

**Comment by Sec-ant** [comment]
> 命令语句是什么呀，作者，试了txt转doc，没看到HTML转epub的命令
`pandoc -s .\input.html -o .\output.epub --verbose`
