### ISSUE TITLE
部分书籍无法爬取

### ISSUE THREAD

**Issue by janebooom** [Sec-ant/weread-scraper#22]
**关于 Bug 的描述**

部分书籍无法爬取，根据观察此类书籍一般都缺少版权页

**抓取的书籍链接**

https://weread.qq.com/web/reader/0473270058addd047f1f76akc4c329b011c4ca4238a0201

**WeRead Scraper 脚本的版本号**

1.2.1

**运行书籍抓取脚本所使用的浏览器**

Chrome 版本 115.0.5790.102

**Comment by Sec-ant** [comment]
这类书籍原始格式是 txt，获取章节内容的请求和 epub 格式的书籍有所区别，1.2.2 版本已修复这个问题。
