### ISSUE TITLE
V1.2.3 没有menu

### ISSUE THREAD

**Issue by abstruse** [Sec-ant/weread-scraper#23]
更新到1.2.3后，menu都没有了，如“Start Scraping”，都看不到了。

**Comment by Sec-ant** [comment]
浏览器详细的版本号说一下

**Comment by abstruse** [comment]
Google Chrome 版本 115.0.5790.114（正式版本） (x86_64)

**Comment by abstruse** [comment]
V1.2.2 Google Chrome 版本 115.0.5790.114（正式版本） (x86_64)，没有问题

**Comment by abstruse** [comment]
![image](https://github.com/Sec-ant/weread-scraper/assets/2641563/7c16af30-6c9a-468c-ab7a-795b0acf9669)

**Comment by abstruse** [comment]
![image](https://github.com/Sec-ant/weread-scraper/assets/2641563/0bbca6f9-fee7-4d06-ae84-3db73daf927d)

**Comment by Sec-ant** [comment]
问题原因已找到，请暂时将 Tampermnkey 插件设置中的“修改内容安全策略（CSP）头信息”设为“全部移除”。未来版本更新将修复这个问题：
![image](https://github.com/Sec-ant/weread-scraper/assets/10386119/2793cdb9-2e8d-49f4-8eec-56f18f8cb309)

**Comment by Sec-ant** [comment]
已修复，请尝试 1.2.4 版本（点击[这里](https://greasyfork.org/scripts/450169@latest/code/WeRead%20Scraper.user.js)安装）是否在不需要修改“修改内容安全策略（CSP）”选项时便可以正常工作

**Comment by abstruse** [comment]
1.2.5 版本,不需要修改“修改内容安全策略（CSP）”选项时，可以工作正常。谢谢！👍
