### ISSUE TITLE
抓取不到章节标题

### ISSUE THREAD

**Issue by whairdo** [Sec-ant/weread-scraper#24]
描述如题。

书籍：https://weread.qq.com/web/reader/09332a205e420d0939968f2

脚本版本号：1.2.5

浏览器：Chrome 版本 115.0.5790.110（正式版本） （64 位）

开发辛苦！这个脚本在kindle退出之后真的帮了我大忙

**Comment by Sec-ant** [comment]
这个书源文件格式是 txt，txt 文档暂时不支持抓章节标题

**Comment by whairdo** [comment]
> 这个书源文件格式是 txt，txt 文档暂时不支持抓章节标题

可否了解一下其中的原理呢？（具备基本的html结构和css知识）

**Comment by Sec-ant** [comment]
> 可否了解一下其中的原理呢？（具备基本的html结构和css知识）

技术或原理上没有什么问题，单纯是代码没写这一块，而且章节相关的还有一些其它改进想一起加上，刚刚改好了。

1.3.0 版本已发布，已支持 txt 格式书籍的章节标题。
