### ISSUE TITLE
扩展支持豆瓣阅读

### ISSUE THREAD

**Issue by yuchen-lea** [Sec-ant/weread-scraper#26]
**描述新功能的设计思路**

不太确定是否超出了本脚本的预期功能范围，不知是否可以复用工作原理到豆瓣阅读，将豆瓣阅读书籍内容导出为 HTML 文件？

**补充说明**

实例：https://read.douban.com/reader/ebook/440483517/?dcs=ebook

**Comment by Sec-ant** [comment]
这个不属于本脚本的预期功能，而且不同平台的处理流程有区别。豆瓣阅读相对比较简单，它并没有对渲染的内容做隐藏，所以应该可以直接用代码读取。如果说要从请求中获取数据可以参考这个仓库：https://github.com/jacksyen/gk7-douban/blob/master/client/scripts/content_script.js

**Comment by yuchen-lea** [comment]
非常感谢给予的支持！也非常感谢提供的工具！不太熟悉前端，我先学习一下~
