### ISSUE TITLE
chapter title are not saved in html file

### ISSUE THREAD

**Issue by love1900905** [Sec-ant/weread-scraper#3]
Some book have chapter title at the beginning, but it's not included into the saved html.

e.g. https://weread.qq.com/web/reader/46b32a1059e99046bb224be
<div class="readerChapterContent fontLevel2">
   <div class="chapterTitle"> 第9章 乐读单参考答案

and this book: https://weread.qq.com/web/reader/d3c32fc071e0b7e1d3c61d2ka3f32db0244a3f390d88bb9
(this page is not the last but not clickable <even manually>)

**Comment by Sec-ant** [comment]
The chapter titles are not rendered on the canvas so acquiring them is not a big problem but whether to put them in the result is debatable. For now, I'd rather keep this script lightweight, easy to read and focusing on the core functions, i.e. scraping the texts that are put on the canvas. Anyway, using HTML as the output format is not very ideal either. I have considered exporting the books into EUPBs that have a wider support and better consistency across platforms while keeping flexibility and editability, and in that case we can talk about chapter titles, TOCs, notes or other things, but it requires me to spend more time on studying the EPUB specs and stuff which now I don't have much time to look into.

Regarding to the non-clickable next-page button, I believe it is a bug from Weread. You can manually click the next page link from the TOC in the sidebar to kick this script off again.

**Comment by love1900905** [comment]
> The chapter titles are not rendered on the canvas so acquiring them is not a big problem (this is also the reason why they're not shown in the result) but whether to put them in the result is debatable. For now, I'd rather keep this script lightweight, easy to read and focusing on the core functions, i.e. scraping the texts that are put on the canvas. Anyway, using HTML as the output format is not very ideal either. I have considered exporting the books into EUPBs that have a wider support and better consistency across platforms while keeping flexibility and editability, and in that case we can talk about chapter titles, TOCs, notes or other things, but it requires me to spend more time on studying the EPUB specs and stuff which now I don't have much time to look into.
> 
> Regarding to the non-clickable next-page button, I believe it is a bug from Weread. You can manually click the next page link from the TOC in the sidebar to kick this script off again.

Glad to known this, thank you again.

Yes, the output html file still need online access to src="https://res.weread.qq.com/wrepub/epub......." for each image, and thus not have too much flexibility as  EPUB.  
btw, for me, I think html format fine, by using FF to print it to PDF and then read in my BOOX, Thus, again, thanks for this really useful script.
