### ISSUE TITLE
注释导致正文版式错乱

### ISSUE THREAD

**Issue by EasyIsAllYouNeed** [Sec-ant/weread-scraper#31]
**关于 Bug 的描述**

请清晰且准确地描述是什么样的 Bug
注释导致部分文字排版错乱

**复现步骤**

复现这个步骤的 Bug 是：

1. 打开…
https://weread.qq.com/web/reader/ca632af0813ab8027g013745k45c322601945c48cce2e120
勾选保存注释，保存为html

**预期行为**
注释不影响正文

请清晰且准确地描述你所认为的预期行为应该是怎样的

**问题截图**
![image](https://github.com/Sec-ant/weread-scraper/assets/121446530/3fc6b7ae-19f3-4d55-bab3-5c58775b24fa)

如果可以的话，请添加截图来辅助说明你遇到的问题

**抓取的书籍链接**

[如：https://weread.qq.com/web/reader/f6432a905b73c0f64797a8dkc81322c012c81e728d9d180](https://weread.qq.com/web/reader/ca632af0813ab8027g013745k45c322601945c48cce2e120)

**Comment by Sec-ant** [comment]
请问 1.4.1 版本还有这个问题吗？我这边没有复现出来。

**Comment by EasyIsAllYouNeed** [comment]
1.4.1可以了，点个赞！！
