### ISSUE TITLE
现在V1爬取的内容都是乱码的，请问有什么方法可以解决吗

### ISSUE THREAD

**Issue by dengsun** [Sec-ant/weread-scraper#32]
由于上班时间有几天时间没有用到weread-scraper了，今天用的过程中发现现在爬取的内容很多都是乱码的，有时候改变一下间隔时间有些部分爬取正常，但大部分还是乱码的，我个人用weread-scraper爬取书籍的原因是需要写作用的，我写作用的软件是obsidian这种双链接的软件，需要在文字中做笔记和做链接，所以需要将书籍导出到obsidain里，目前的需求就只需要导出为html而已，不太需要Epub和pdf版本，如果作者v2的功能已经可以实现爬取为html，且没有乱码，希望作者可以提供给我使用下哈，有偿！不希望作者的努力白费。我也觉得v2目前不要大规模公开，小规模付费使用即可，使用人数太多也很容易gua。

**Comment by dengsun** [comment]
![](https://cdn.jsdelivr.net/gh/dengsun/PicGoRes@master/img3/aea3c8c07f025e4bc71d06e64cad903.png)

**Comment by Sec-ant** [comment]
我会先尝试在 v1 上修复，v2 暂时还没办法开放用

**Comment by dengsun** [comment]
期待楼主的更新！

**Comment by Sec-ant** [comment]
1.4.1 版本已修复：https://greasyfork.org/scripts/450169@latest/code/weread-scraper.user.js

**Comment by dengsun** [comment]
楼主牛逼，效率太高了，太厉害了！
