### ISSUE TITLE
用完插件后会导致微信读书被封号

### ISSUE THREAD

**Issue by ljy-life** [Sec-ant/weread-scraper#33]
用完插件后会导致微信读书被封号

**Comment by Sec-ant** [comment]
请先尝试向微信申诉，我个人开发能力有限，也不能保证在微信采取如此激进封杀措施后还能够继续维护下去。

**Comment by Sec-ant** [comment]
1.4.2 已暂时修复这个问题，但是我无法保证后续微信读书会不会有其它新的措施来检测并封禁，请大家自行注意。
