### ISSUE TITLE
please reduce some meaningless content

### ISSUE THREAD

**Issue by adyliu** [Sec-ant/weread-scraper#4]
special for page `https://weread.qq.com/web/reader/f2e328e072182b15f2e7179kc4c329b011c4ca4238a0201`

content like  that
```
<p class="chapterContent_p" data-wr-co="2"><span data-wr-id="layout" data-wr-co="2">你</span><span data-wr-id="layout" data-wr-co="3">好</span><span data-wr-id="layout" data-wr-co="4">，</span><span data-wr-id="layout" data-wr-co="5">我</span><span data-wr-id="layout" data-wr-co="6">是</span><span data-wr-id="layout" data-wr-co="7">冯</span><span data-wr-id="layout" data-wr-co="8">唐</span><span data-wr-id="layout" data-wr-co="9">。</span>
```

only prints 8 words:

```
你好，我是冯唐。
```

**Comment by Sec-ant** [comment]
Removing those attributes may cause some styling problems, if you are concerned with the output size, try something like [https://github.com/terser/html-minifier-terser] to minify the output.
