### ISSUE TITLE
一些书不同页的顺序会出错

### ISSUE THREAD

**Issue by evoke322** [Sec-ant/weread-scraper#8]
当一个章节有下一页的情况，在保存的时候顺序会乱，比如[这本](https://weread.qq.com/web/bookDetail/5e2322a0813ab7dd3g013d77)

**Comment by Sec-ant** [comment]
已注意到这个问题，欢迎贡献代码修复

**Comment by Sec-ant** [comment]
更新一下此问题产生的原因：微信阅读在获取下一个章节内容时，会有一个短暂过程将下一个章节的非第一页的内容渲染在 HTML 中，然后才会渲染下一个章节的第一页的内容，人眼/浏览器渲染引擎无法在如此短暂的时间内察觉到/渲染这部分内容，而本脚本使用的 Mutation Observer 则会误以为那个短暂的非第一页的内容即为接下来要渲染的内容，因此造成了内容顺序错乱或缺失。

最直观的解决办法是增加延时，等待一段时间页面不发生变化后再决定要保留哪部分内容，但是延时容易使程序出现竞争冒险、或效率下降的问题。

更可取的方法是找到并截获微信代码中对内容做替换的语句，但是这个难度比较高。

**Comment by Sec-ant** [comment]
v1.0.0 版本重写了代码，这个问题应该解决了

**Comment by evoke322** [comment]
目测应该没问题了，thanks.
