### ISSUE TITLE
关于每个章节一个<div class="preRenderContent">的需求

### ISSUE THREAD

**Issue by janebooom** [Sec-ant/weread-scraper#9]
非常感谢大佬的脚本！我平时习惯用kindle看书，但是微信读书的kindle网页版并不好用，需要一直连着网。于是我用大佬的脚本将书籍下载后，通过calibre转化成azw3格式，导入kindle中，非常好用。

但是在转化的时候，生成目录会有问题。我想是否可以将微信读书上每一章的内容，创建在一个`<div class="preRenderContent">`中，现在很多书籍只是是下一页就会新建`<div class="preRenderContent">`。如果每个`<div class="preRenderContent">`是一个章节的话，我就可以利用微信读书的章节信息，新建目录，目录就会非常准确。

辛苦大佬看看是否可以实现，感谢！

**Comment by Sec-ant** [comment]
已发布 1.1.0 版本，目前同一章节（任意级别）不同页面内容会放在同一个 `<div class="preRenderContainer readerChapterContent">` 容器中。`preRenderContainer` 这个 `className` 有可能会在后面弃用，如果需要做一些后处理，建议用 `readerChapterContent` 这个 `className`.

**Comment by Sec-ant** [comment]
@janebooom 这个版本是否解决了章节与目录对应的问题？

**Comment by janebooom** [comment]
@Sec-ant 已经解决，感谢🙏
